version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_NAME=FINALAuto
      - DB_USER=postgres
      - DB_PASS=Max342213
      - DB_HOST=db
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: FINALAuto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Max342213
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d  # если есть init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
